### ISSUE TITLE
Requires quotes around numbers, also crashes

### ISSUE THREAD

**Issue by AmitBokoDev** [paasi6666/Bot-Blocker#3]
Your code ```if inp == "1":``` requires the answer to be literally ```"1"``` , you should change it to ```if inp == 1:```.
Also, it crashes after choosing a browser regardless of choice-
```
You chose Firefox, installing driver..
Traceback (most recent call last):
  File ".\main.py", line 44, in <module>
    chooseBrowser()
  File ".\main.py", line 13, in chooseBrowser
    from webdriver_manager.firefox import GeckoDriverManager
  File "C:\Python27\lib\site-packages\webdriver_manager\firefox.py", line 2, in <module>
    from webdriver_manager.driver import GeckoDriver
  File "C:\Python27\lib\site-packages\webdriver_manager\driver.py", line 77
    self.auth_header = {'Authorization': f'token {self._os_token}'}
                                                                 ^
SyntaxError: invalid syntax
```
love the idea tho and it looked like it worked before the new feature

**Comment by AmitBokoDev** [comment]
was using an old python version, my bad
